name: Build docs

on:
  push:
    branches:
      - main
    paths:
      - docs/**/*.*
      - src/**/*.*
      - .github/workflows/docs.yml
      - mkdocs.yml
  workflow_dispatch:

jobs:
  deploy:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.13"

      - name: Install the project
        run: uv sync --all-extras --locked

      - name: Deploy docs
        run: uv run mkdocs gh-deploy --force